# Generated by Django 4.0.1 on 2022-01-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
